apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "movie-web-ui.fullname" . }}
  labels:
    {{- include "movie-web-ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "movie-web-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "movie-web-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "movie-web-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: UI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: movie-web-ui-creds
                  key: username
            - name: UI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: movie-web-ui-creds
                  key: password
            - name: MOVIE_API_HOST    # the name of the movie-api service in the cluster
              value: movie-api
            - name: MOVIE_API_PORT
              value: '8009'

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          volumeMounts:
            - mountPath: /app/web_ui/volume
              name: plex-media
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /readiness
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: plex-media
        persistentVolumeClaim:
          claimName: plex-media-pvc
