apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: plex-media-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.0.45
  share: /volumes/plex-drive
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1