apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-pvc
  labels:
    app: plex-label
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: plex-media-nfs
  resources:
    requests:
      storage: 10Gi