apiVersion: v1
kind: Service
metadata:
  name: {{ include "movie-api-chart.fullname" . }}
  labels:
    {{- include "movie-api-chart.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8009
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ default "8009" .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: movie-api
  selector:
    {{- include "movie-api-chart.selectorLabels" . | nindent 4 }}

